product-name: p-compliance-scanner
product-properties:
  .properties.benchmarks:
    value:
    - base
    - recommended
    - strict
    - stig
  .properties.ntp_server:
    value: ((properties.ntp_server))
  .properties.openfile_limit:
    value: 2048
  .properties.scan_report_formats:
    value:
    - log
    - xml
    - html
  .properties.scanner_timeout:
    value: ((properties.scanner_timeout))
  .properties.syslog_host:
    value: ((properties.syslog_host))
  .properties.syslog_port:
    value: ((properties.syslog_port))
network-properties:
  network:
    name: ((network_name))
  other_availability_zones:
  - name: ((singleton_availability_zone))
  singleton_availability_zone:
    name: ((singleton_availability_zone))
resource-config:
  oscap_store:
    instances: ((oscap_store_instances))
    instance_type:
      id: ((oscap_store_instance_type))
errand-config:
  scan_results:
    post-deploy-state: ((scan_results_state))
